name: pomodoro
description: Tempus â€” Timer Pomodoro profissional
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.5
  audioplayers: ^6.5.1
  shared_preferences: ^2.5.3
  provider: ^6.1.2
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/alarm.mp3
